# Navigation
nav:
  - Home: index.md
  - Guides & Tools:
      - Better Terminal Experience: guides/BetterTerminal.md
      - Pi-Hole With DNS Over HTTPS: guides/pihole_dns.md
      - Wifi QR Image Generator: guides/wifiQrGenerator.md
      - Gmail Markas Read: guides/gmailMarkAsRead.md
      - Raspberry Pi 3 Tor Access Point: raspberryPi/TOR-Pi.md
      - Useful Links & Tools: guides/usefulLinks_Tools.md
      - Synology DSM: guides/synology.md
      - Ubiquiti EdgeRouter & Unifi: guides/ubiquiti.md
      - Proxmox Virtualization: guides/proxmox.md
  - Linux:
      - General: linux/general/general.md
      - SSH Service Security: linux/SSH_Service_Security.md
      - Centos 7: linux/centos7.md
      - Centos 8: linux/centos8.md
      - Ubuntu & Debian: linux/ubuntu.md
      - Files: linux/general/files.md
      - Memory & Swap: linux/general/memorySwap.md
      - Linux LVM Partitions: linux/lvm.md
      - Linux Services:
          - cPanel & WHM: linux/services/cpanel.md
          - CSF Firewall: linux/services/csf.md
          - Nginx: linux/services/nginx.md
          - Apache: linux/services/apache.md
          - Sophos Firewall: linux/services/sophos.md
          - Wordpress: linux/services/wordpress.md
          - Esxi: linux/services/esxi.md
          - Plesk: linux/services/plesk.md
          - Postfix: linux/services/postfix.md
  - macOS:
      - General: macOS/general.md
      - UI Tweaks: macOS/ui.md
      - System Tweaks: macOS/system.md
      - Applications Tweaks: macOS/applications.md
      - BrewUp - macOS Auto Update: macOS/brewup.md
      - Python macOS The Right Way: macOS/pythonTheRightWay.md
  - Raspberry Pi:
      - General: raspberryPi/piGeneral.md
      - Raspberry Pi 3 Tor Access Point: raspberryPi/TOR-Pi.md
      - Raspberry Pi Magic Mirror: raspberryPi/MagicMirror.md
  - Development:
      - Git: development/git.md
      - Docker: development/dockerGeneral.md
      - Python: development/python.md
      - Ruby: development/ruby.md
      - npm & node: development/npm.md
      - Personal Docker Containers: development/dockerContainers.md
  - Windows:
      - Windows General: windows/windowsGeneral.md
      - Windows Guides and How-To: windows/windowsGuides.md
  - Penetration-Testing:
      - General: penTesting/general.md
      - Kali Linux: penTesting/kaliLinux.md
      - IDD Generator & Validator: penTesting/iddGenerator.md
      - Click-Jacking Test: penTesting/clickJacking.md
      - htpasswd Generator: penTesting/htpasswd_Generator.md
      - Android Penetration Testing: penTesting/androidPT.md
  - Markdown CheatSheet:
      - Welcome: markdownCheatSheet/welcome.md
      - Headings: markdownCheatSheet/headings.md
      - Emphasis: markdownCheatSheet/emphasis.md
      - Line Breaks: markdownCheatSheet/lineBreaks.md
      - Lists: markdownCheatSheet/lists.md
      - Tables: markdownCheatSheet/tables.md
      - Links: markdownCheatSheet/links.md
      - Images: markdownCheatSheet/images.md
      - Admonition: markdownCheatSheet/admonition.md
      - Block Quotes: markdownCheatSheet/blockQuotes.md
      - Emojis List: markdownCheatSheet/emoji.md
      - Embed External Sources: markdownCheatSheet/embedExternalSources.md
      - Metadata Per Page: markdownCheatSheet/metaData.md
  - About:
      - About: about/about.md
      - Donation: about/donation.md
      - License: about/license.md

# Project information
site_name: 3os
site_url: https://3os.org/
site_author: Stas Yakobov
site_description: >-
  Collocation of technical documentation, guides, knowledge, examples and
  tips...

# Repository
repo_name: fire1ce/3os.org
repo_url: https://github.com/fire1ce/3os.org/
edit_uri: edit/master/src/

# Theme Configuration
theme:
  name: material
  custom_dir: overrides
  language: en
  features:
    - tabs
    - instant
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/chart-donut-variant
  favicon: assets/favicon.png

# Plugins
plugins:
  - search:
      prebuild_index: true
  - minify:
      minify_html: true
  # - git-revision-date-localized

# Social Links and Comments
extra:
  disqus: 3os
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/fire1ce
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/stas-yakobov
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/3os.org

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.sane_lists
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.abbr
  - markdown.extensions.meta
  - markdown.extensions.tables
  - markdown.extensions.toc:
      toc_depth: '2'
      permalink: '🔗'
      separator: '_'
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.extra
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: fire1ce
      repo: 3os.org
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pyembed.markdown

# Google Analytics
google_analytics:
  - 'UA-122318911-1'
  - 'auto'

# Copyright
copyright: 'Copyright &copy; 3os.org @2018-2020'
